pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform-0.11.13"
    }
    parameters {
        string(name: 'WORKSPACE', defaultValue: 'development', description:'workspace to use in Terraform')
    }
    environment {
        TF_HOME = tool('terraform-0.11.13')
        VSPHERE_LOGON = credentials('vSphere')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
    }
    stages {
        stage('NetworkInit'){
            steps {
                dir('Terraform-Skool/Exercise3/'){
                    sh 'terraform --version'
                    sh "terraform init -input=false -plugin-dir=/var/jenkins_home/terraform_plugins"
                    sh "echo \$PWD"
                    sh "whoami"
                }
            }
        }
        stage('NetworkPlan'){
            steps {
                dir('Terraform-Skool/Exercise3/'){
                    script {
                        try {
                           sh "terraform workspace new ${params.WORKSPACE}"
                        } catch (err) {
                            sh "terraform workspace select ${params.WORKSPACE}"
                        }
                        sh "terraform plan -var 'username=$VSPHERE_LOGON_USR' -var 'password=$VSPHERE_LOGON_PSW' -out terraform-networking.tfplan;echo \$? > status"
                        stash name: "terraform-networking-plan", includes: "terraform-networking.tfplan"
                    }
                }
            }
        }
        stage('NetworkApply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        dir('Terraform-Skool/Exercise3/'){
                            unstash "terraform-networking-plan"
                            sh "terraform destroy -var 'username=$VSPHERE_LOGON_USR' -var 'password=$VSPHERE_LOGON_PSW' -force"
                            currentBuild.result = 'UNSTABLE'
                        }                        
                    }
                    if(apply){
                        dir('Terraform-Skool/Exercise3/'){
                            unstash "terraform-networking-plan"
                            sh 'terraform apply terraform-networking.tfplan'
                        }
                    }
                }
            }
        }

    }
}